apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: piomin/caller-service
      jib: {}
  local: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - k8s/*