apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
    - image: gcr.io/teak-backup-270111/callme-service
      jib: {}
  local: {}
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - k8s/*
